### ISSUE TITLE
Overlapping section heading with the image and misplaced text in mobile resolution in homepage

### ISSUE THREAD

**Issue by shreyaagrawal0809** [CivicDataLab/fiscal_data_explorer_frontend#116]
<img width="377" alt="Screenshot 2022-10-08 at 12 30 56 PM" src="https://user-images.githubusercontent.com/35596028/194694558-cb7a7c7d-94bf-4245-898a-bb9ecd372345.png">

**Comment by GeorgeET15** [comment]
Hi, i would like to work on this issue can you assign this to me. Thank you

**Comment by anuragh2002** [comment]
Hey @shreyaagrawal0809 I would like to work on this issue. Can you please assign it to me?

**Comment by GeorgeET15** [comment]
Hi, while running the dev server its not working

**Comment by shivamragnar** [comment]
Hey @GeorgeET15 try removing `package-lock.json`and `node_modules`, then run `npm install`, it should work.

**Comment by GeorgeET15** [comment]
![Not working](https://user-images.githubusercontent.com/72024420/194814935-2492a0d2-aee8-42f2-9160-e7bf9b327c96.png)


I am not able to access the receipts page. It's blank

**Comment by shivamragnar** [comment]
I think this section works fine, if you load it directly into mobile device or device with different widths. But I am guessing, you might be trying to go from desktop mode to mobile mode, which might have caused it. Anyway I have updated the large content gaps, but this issue seems fine to me. @shreyaagrawal0809
